pipeline {
    agent any

    environment {
        // 본인의 username으로 하실 분은 수정해주세요.
        DOCKERHUB_USERNAME = '1pro'
        GITHUB_URL = 'https://github.com/k8s-1pro/kubernetes-anotherclass-sprint3.git'

        // 실습 넘버링
        CLASS_NUM = '3223'
        // 버전
        APP_VERSION = '3.0.0'
    }
    
    stages {

        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                    extensions: [[$class: 'SparseCheckoutPaths',
                    sparseCheckoutPaths: [[path: "/${CLASS_NUM}"]]]],
					userRemoteConfigs: [[url: "${GITHUB_URL}"]])
            }
        }

        stage('쿠버네티스 배포') {
            steps {
                // K8S 배포
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/namespace.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/configmap.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/secret.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/ingress-backend.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/ingress-frontend.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/service-backend.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/service-frontend.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/deployment-backend.yaml"
                sh "kubectl apply -f ./${CLASS_NUM}/deploy/k8s/deployment-frontend.yaml"
            }
        }
    }
}